# Generated by Django 2.2 on 2020-10-17 16:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogsNewsModule', '0002_postapi'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PostApi',
        ),
    ]
