# Generated by Django 3.2.9 on 2021-12-13 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogsNewsModule', '0004_auto_20211213_0147'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='instagram_url',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='profile_pic',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
        migrations.AddField(
            model_name='profile',
            name='website_url',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
